#!/bin/bash
# Auto-generated build script for compiled always blocks
# Generated by ELOPT ModuleCodeGenerator

CXX=${CXX:-g++}
INCLUDE_FLAGS="-I/home/prajwal/chipdesigner-ai/pulse/elsim/include -DELSIM_CODEGEN_INLINE"
# Add -undefined dynamic_lookup on macOS for runtime symbol resolution
# -w suppresses warnings to avoid false test failures from warning text
if [[ "$OSTYPE" == "darwin"* ]]; then
    CXXFLAGS="-std=c++17 -O3 -march=native -flto -w -fPIC -shared -undefined dynamic_lookup $INCLUDE_FLAGS"
else
    CXXFLAGS="-std=c++17 -O3 -march=native -flto -w -fPIC -shared $INCLUDE_FLAGS"
fi
OUTPUT_DIR="work/codegen"

# Compile each generated file into a shared library
echo "Compiling work/codegen/gen_simple_clock.cpp..."
$CXX $CXXFLAGS -o "$OUTPUT_DIR/gen_simple_clock.so" "work/codegen/gen_simple_clock.cpp" 2>/dev/null
if [ $? -ne 0 ]; then
    echo "Failed to compile work/codegen/gen_simple_clock.cpp"
    exit 1
fi

echo "All files compiled successfully"
