#!/bin/bash
# Auto-generated build script for compiled always blocks
# Generated by ELOPT ModuleCodeGenerator

CXX=${CXX:-g++}
INCLUDE_FLAGS="-Iwork/codegen -I/home/prajwal/chipdesigner-ai/pulse/elsim/include -DELSIM_CODEGEN_INLINE"
# Add -undefined dynamic_lookup on macOS for runtime symbol resolution
# -w suppresses warnings to avoid false test failures from warning text
if [[ "$OSTYPE" == "darwin"* ]]; then
    CXXFLAGS="-std=c++17 -O1 -w -fPIC -shared -undefined dynamic_lookup $INCLUDE_FLAGS"
else
    CXXFLAGS="-std=c++17 -O1 -w -fPIC -shared $INCLUDE_FLAGS"
fi
OUTPUT_DIR="work/codegen"

# Compile each generated file into a shared library (parallel, with caching)
PIDS=()
FILES=()
FAILED=0

SO_FILE="$OUTPUT_DIR/gen_control_unit.so"
CPP_FILE="work/codegen/gen_control_unit.cpp"
if [ -f "$SO_FILE" ] && [ "$SO_FILE" -nt "$CPP_FILE" ]; then
    : # up to date
else
    echo "Compiling work/codegen/gen_control_unit.cpp..."
    ( $CXX $CXXFLAGS -o "$SO_FILE" "$CPP_FILE" 2>/dev/null ) &
    PIDS+=($!); FILES+=("work/codegen/gen_control_unit.cpp")
fi

SO_FILE="$OUTPUT_DIR/gen_instruction_decoder.so"
CPP_FILE="work/codegen/gen_instruction_decoder.cpp"
if [ -f "$SO_FILE" ] && [ "$SO_FILE" -nt "$CPP_FILE" ]; then
    : # up to date
else
    echo "Compiling work/codegen/gen_instruction_decoder.cpp..."
    ( $CXX $CXXFLAGS -o "$SO_FILE" "$CPP_FILE" 2>/dev/null ) &
    PIDS+=($!); FILES+=("work/codegen/gen_instruction_decoder.cpp")
fi

SO_FILE="$OUTPUT_DIR/gen_alu.so"
CPP_FILE="work/codegen/gen_alu.cpp"
if [ -f "$SO_FILE" ] && [ "$SO_FILE" -nt "$CPP_FILE" ]; then
    : # up to date
else
    echo "Compiling work/codegen/gen_alu.cpp..."
    ( $CXX $CXXFLAGS -o "$SO_FILE" "$CPP_FILE" 2>/dev/null ) &
    PIDS+=($!); FILES+=("work/codegen/gen_alu.cpp")
fi

SO_FILE="$OUTPUT_DIR/gen_arithmetic_unit.so"
CPP_FILE="work/codegen/gen_arithmetic_unit.cpp"
if [ -f "$SO_FILE" ] && [ "$SO_FILE" -nt "$CPP_FILE" ]; then
    : # up to date
else
    echo "Compiling work/codegen/gen_arithmetic_unit.cpp..."
    ( $CXX $CXXFLAGS -o "$SO_FILE" "$CPP_FILE" 2>/dev/null ) &
    PIDS+=($!); FILES+=("work/codegen/gen_arithmetic_unit.cpp")
fi

SO_FILE="$OUTPUT_DIR/gen_logic_unit.so"
CPP_FILE="work/codegen/gen_logic_unit.cpp"
if [ -f "$SO_FILE" ] && [ "$SO_FILE" -nt "$CPP_FILE" ]; then
    : # up to date
else
    echo "Compiling work/codegen/gen_logic_unit.cpp..."
    ( $CXX $CXXFLAGS -o "$SO_FILE" "$CPP_FILE" 2>/dev/null ) &
    PIDS+=($!); FILES+=("work/codegen/gen_logic_unit.cpp")
fi

SO_FILE="$OUTPUT_DIR/gen_shift_unit.so"
CPP_FILE="work/codegen/gen_shift_unit.cpp"
if [ -f "$SO_FILE" ] && [ "$SO_FILE" -nt "$CPP_FILE" ]; then
    : # up to date
else
    echo "Compiling work/codegen/gen_shift_unit.cpp..."
    ( $CXX $CXXFLAGS -o "$SO_FILE" "$CPP_FILE" 2>/dev/null ) &
    PIDS+=($!); FILES+=("work/codegen/gen_shift_unit.cpp")
fi

SO_FILE="$OUTPUT_DIR/gen_register_file.so"
CPP_FILE="work/codegen/gen_register_file.cpp"
if [ -f "$SO_FILE" ] && [ "$SO_FILE" -nt "$CPP_FILE" ]; then
    : # up to date
else
    echo "Compiling work/codegen/gen_register_file.cpp..."
    ( $CXX $CXXFLAGS -o "$SO_FILE" "$CPP_FILE" 2>/dev/null ) &
    PIDS+=($!); FILES+=("work/codegen/gen_register_file.cpp")
fi

SO_FILE="$OUTPUT_DIR/gen_reg_bank.so"
CPP_FILE="work/codegen/gen_reg_bank.cpp"
if [ -f "$SO_FILE" ] && [ "$SO_FILE" -nt "$CPP_FILE" ]; then
    : # up to date
else
    echo "Compiling work/codegen/gen_reg_bank.cpp..."
    ( $CXX $CXXFLAGS -o "$SO_FILE" "$CPP_FILE" 2>/dev/null ) &
    PIDS+=($!); FILES+=("work/codegen/gen_reg_bank.cpp")
fi

SO_FILE="$OUTPUT_DIR/gen_memory_interface.so"
CPP_FILE="work/codegen/gen_memory_interface.cpp"
if [ -f "$SO_FILE" ] && [ "$SO_FILE" -nt "$CPP_FILE" ]; then
    : # up to date
else
    echo "Compiling work/codegen/gen_memory_interface.cpp..."
    ( $CXX $CXXFLAGS -o "$SO_FILE" "$CPP_FILE" 2>/dev/null ) &
    PIDS+=($!); FILES+=("work/codegen/gen_memory_interface.cpp")
fi

SO_FILE="$OUTPUT_DIR/gen_cache_controller.so"
CPP_FILE="work/codegen/gen_cache_controller.cpp"
if [ -f "$SO_FILE" ] && [ "$SO_FILE" -nt "$CPP_FILE" ]; then
    : # up to date
else
    echo "Compiling work/codegen/gen_cache_controller.cpp..."
    ( $CXX $CXXFLAGS -o "$SO_FILE" "$CPP_FILE" 2>/dev/null ) &
    PIDS+=($!); FILES+=("work/codegen/gen_cache_controller.cpp")
fi

SO_FILE="$OUTPUT_DIR/gen_cache_line.so"
CPP_FILE="work/codegen/gen_cache_line.cpp"
if [ -f "$SO_FILE" ] && [ "$SO_FILE" -nt "$CPP_FILE" ]; then
    : # up to date
else
    echo "Compiling work/codegen/gen_cache_line.cpp..."
    ( $CXX $CXXFLAGS -o "$SO_FILE" "$CPP_FILE" 2>/dev/null ) &
    PIDS+=($!); FILES+=("work/codegen/gen_cache_line.cpp")
fi

# Wait for all parallel compilations
for i in "${!PIDS[@]}"; do
    if ! wait "${PIDS[$i]}"; then
        echo "Failed to compile ${FILES[$i]}"
        FAILED=1
    fi
done
if [ $FAILED -ne 0 ]; then exit 1; fi
echo "All files compiled successfully"
