// Auto-generated C++ code for instance: simple_clock
// Generated by ELOPT ModuleCodeGenerator
// DO NOT EDIT - This file is automatically generated

#include <cstdint>
#include <cstring>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <vector>
#include <map>
#include <algorithm>
#include <string>
// S91: Minimal ExecutionContext with flat_signal_mem for inline read_signal
class Instance; class SignalStateManager; class EventScheduler;
class NBAScheduler; class Process; class Simulator;
class ProcessDatabase; class ClassRegistry; class VirtualInterface;
struct ExecutionContext {
    Instance* instance; SignalStateManager* signal_states;
    EventScheduler* scheduler; NBAScheduler* nba_scheduler;
    Process* current_process; Simulator* simulator;
    ProcessDatabase* process_db; ClassRegistry* class_registry;
    double real_delay; uint64_t* flat_signal_mem;
    uint64_t* flat_signal_bval;
    uint64_t* flat_nba_mem; uint8_t* flat_nba_pending;
    uint32_t* flat_nba_dirty_list; uint32_t flat_nba_dirty_count;
};
static inline __attribute__((always_inline)) uint64_t read_signal(ExecutionContext* ctx, int signal_id) {
    return ctx->flat_signal_mem[signal_id];
}
static uint64_t _xprop_bval;
static inline __attribute__((always_inline)) uint64_t read_signal_xp(ExecutionContext* ctx, int signal_id) {
    _xprop_bval |= ctx->flat_signal_bval[signal_id];
    return ctx->flat_signal_mem[signal_id];
}
// IEEE 4-state bitwise: per-bit X propagation
static inline void bitwise_and_4state(uint64_t aa, uint64_t ab, uint64_t ba, uint64_t bb, uint64_t* ra, uint64_t* rb) {
    uint64_t a1 = aa & ~ab, b1 = ba & ~bb;
    uint64_t a0 = ~aa & ~ab, b0 = ~ba & ~bb;
    *ra = a1 & b1; *rb = ~(a0 | b0) & ~(a1 & b1);
}
static inline void bitwise_or_4state(uint64_t aa, uint64_t ab, uint64_t ba, uint64_t bb, uint64_t* ra, uint64_t* rb) {
    uint64_t a1 = aa & ~ab, b1 = ba & ~bb;
    uint64_t a0 = ~aa & ~ab, b0 = ~ba & ~bb;
    *ra = a1 | b1; *rb = ~(a1 | b1) & ~(a0 & b0);
}
static inline void bitwise_xor_4state(uint64_t aa, uint64_t ab, uint64_t ba, uint64_t bb, uint64_t* ra, uint64_t* rb) {
    uint64_t def = ~ab & ~bb;
    *ra = (aa ^ ba) & def; *rb = ~def;
}
static inline __attribute__((always_inline)) void write_signal_nba(ExecutionContext* ctx, int signal_id, uint64_t value, int width) {
    (void)width;
    ctx->flat_nba_mem[signal_id] = value;
    if (!ctx->flat_nba_pending[signal_id]) {
        ctx->flat_nba_pending[signal_id] = 1;
        ctx->flat_nba_dirty_list[ctx->flat_nba_dirty_count++] = signal_id;
    }
}

// Runtime functions provided by ELSIM
extern "C" {
    // Signal access
    void write_signal_blocking(ExecutionContext* ctx, int signal_id, uint64_t value, int width);
    uint64_t read_signal_by_name(ExecutionContext* ctx, const char* name);
    
    // Bit-select and part-select writes
    void write_signal_bit_blocking(ExecutionContext* ctx, int signal_id, int bit_idx, uint64_t value, int width);
    void write_signal_bit_continuous(ExecutionContext* ctx, int signal_id, int bit_idx, uint64_t value, int width);
    void write_signal_bit_nba(ExecutionContext* ctx, int signal_id, int bit_idx, uint64_t value, int width);
    void write_signal_range_blocking(ExecutionContext* ctx, int signal_id, int msb, int lsb, uint64_t value, int width);
    void write_signal_range_continuous(ExecutionContext* ctx, int signal_id, int msb, int lsb, uint64_t value, int width);
    void write_signal_range_nba(ExecutionContext* ctx, int signal_id, int msb, int lsb, uint64_t value, int width);
    
    // Memory access (for unpacked arrays)
    uint64_t read_memory(ExecutionContext* ctx, int base_id, int addr);
    void write_memory_blocking(ExecutionContext* ctx, int base_id, int addr, uint64_t value);
    void write_memory_nba(ExecutionContext* ctx, int base_id, int addr, uint64_t value);
    
    // Continuous assign (records signal for propagation)
    void write_signal_continuous(ExecutionContext* ctx, int signal_id, uint64_t value, int width);
    void write_signal_4state_continuous(ExecutionContext* ctx, int signal_id, uint64_t aval, uint64_t bval, int width);
    void copy_signal_continuous(ExecutionContext* ctx, int dst_id, int src_id, int width);
    
    // Simulation time (for $time)
    uint64_t get_sim_time(ExecutionContext* ctx);
    uint64_t get_sim_time_precision(ExecutionContext* ctx);
    uint64_t convert_user_to_precision(ExecutionContext* ctx, uint64_t user_time);
    
    // Simulation control
    void sim_finish(ExecutionContext* ctx);
    void sim_stop(ExecutionContext* ctx);
    // PLI callback region registration (§4 scheduling semantics)
    void sim_register_pli_callback(ExecutionContext* ctx, int type, void (*fn)(void*), void* userdata);
    
    // Fractional delay support
    void set_real_delay(ExecutionContext* ctx, double delay_value);
    
    // VCD dump support
    void sim_dumpfile(ExecutionContext* ctx, const char* filename);
    void sim_dumpvars(ExecutionContext* ctx, int level, int signal_id);
    void sim_dumpflush(ExecutionContext* ctx);
    void sim_dumpoff(ExecutionContext* ctx);
    void sim_dumpon(ExecutionContext* ctx);
    void sim_dumpall(ExecutionContext* ctx);
    void sim_set_dump_limit(ExecutionContext* ctx, uint64_t bytes);
    void sim_printtimescale(ExecutionContext* ctx);
    void sim_procedural_assign(ExecutionContext* ctx, int signal_id, uint64_t value, int width);
    void sim_deassign(ExecutionContext* ctx, int signal_id);
    void sim_force(ExecutionContext* ctx, int signal_id, uint64_t value, int width);
    void sim_release(ExecutionContext* ctx, int signal_id);
    void sim_trigger_event(ExecutionContext* ctx, int signal_id);
    
    // Time formatting
    void sim_timeformat(int units, int precision, const char* suffix, int min_width);
    const char* sim_format_time(ExecutionContext* ctx, uint64_t value_user);
    const char* sim_format_time_w(ExecutionContext* ctx, uint64_t value_user, int width);
    
    // Fork-join support
    void sim_spawn_codegen_process(ExecutionContext* ctx, void* func);
    void sim_fork_begin(ExecutionContext* ctx, int join_type);
    void sim_disable_fork(ExecutionContext* ctx);
    int sim_wait_fork(ExecutionContext* ctx);
    
    // Memory initialization
    void readmemh(ExecutionContext* ctx, const char* filename, int mem_id);
    void readmemb(ExecutionContext* ctx, const char* filename, int mem_id);
    void writememh(ExecutionContext* ctx, const char* filename, int mem_id);
    
    // File I/O
    uint64_t sim_fopen(ExecutionContext* ctx, const char* filename, const char* mode);
    void sim_fclose(ExecutionContext* ctx, uint64_t fd);
    uint64_t sim_fgetc(ExecutionContext* ctx, uint64_t fd);
    uint64_t sim_fgets(ExecutionContext* ctx, uint64_t str_signal, uint64_t fd);
    uint64_t sim_ftell(ExecutionContext* ctx, uint64_t fd);
    uint64_t sim_feof(ExecutionContext* ctx, uint64_t fd);
    uint64_t sim_ferror(ExecutionContext* ctx, uint64_t fd);
    void sim_fseek(ExecutionContext* ctx, uint64_t fd, int64_t offset, int whence);
    void sim_rewind(ExecutionContext* ctx, uint64_t fd);
    void sim_ungetc(ExecutionContext* ctx, int c, uint64_t fd);
    int sim_fscanf_int(ExecutionContext* ctx, uint64_t fd, int* values, int count);
    FILE* sim_get_file(uint64_t handle);
    
    // String support
    void write_string_signal(ExecutionContext* ctx, uint64_t str_signal, const char* value);
    void write_packed_string(ExecutionContext* ctx, int signal_id, const char* str);
    const char* read_string_signal(ExecutionContext* ctx, uint64_t str_signal);
    const char* read_packed_string(ExecutionContext* ctx, int signal_id);
    int string_equals(ExecutionContext* ctx, uint64_t str_signal, const char* literal);
    const char* str_toupper(const char* s);
    const char* str_tolower(const char* s);
    const char* str_substr(const char* s, int pos, int len);
    
    // Plusargs
    int test_plusargs(ExecutionContext* ctx, const char* arg);
    int value_plusargs(ExecutionContext* ctx, const char* format, void* value);
    
    // Bit manipulation
    uint64_t extract_bits(uint64_t value, int msb, int lsb);
    uint64_t set_bits(uint64_t orig, uint64_t value, int msb, int lsb);
    uint64_t replicate_bits(uint64_t value, int width, int count);
    
    // Monitor support
    void sim_monitor_setup(void* ctx, void (*func)(void*), int* sig_ids, int num_sigs);
    void sim_monitor_on(void* ctx);
    void sim_monitor_off(void* ctx);
    
    // Event control - wait for signal edge
    // edge_type: 1=posedge, 2=negedge, 3=both
    void wait_for_edge(ExecutionContext* ctx, int signal_id, int edge_type);
    
    // Wait statement support
    int wait_for_condition(ExecutionContext* ctx, uint64_t condition_value);
    void wait_for_signal(ExecutionContext* ctx, int signal_id);
    
    // Array support (for foreach loops)
    int get_array_size(ExecutionContext* ctx, int signal_id);
    
    // 4-state logic support
    uint64_t read_signal_4state(ExecutionContext* ctx, int signal_id, uint64_t* bval_out);
    void write_signal_4state_blocking(ExecutionContext* ctx, int signal_id, uint64_t aval, uint64_t bval, int width);
    void write_signal_4state_nba(ExecutionContext* ctx, int signal_id, uint64_t aval, uint64_t bval, int width);
    uint64_t case_eq_4state(uint64_t a_aval, uint64_t a_bval, uint64_t b_aval, uint64_t b_bval);
    uint64_t case_ne_4state(uint64_t a_aval, uint64_t a_bval, uint64_t b_aval, uint64_t b_bval);
    void logic_eq_4state(uint64_t a_aval, uint64_t a_bval, uint64_t b_aval, uint64_t b_bval, uint64_t* result_aval, uint64_t* result_bval, int is_signed);
    void logic_ne_4state(uint64_t a_aval, uint64_t a_bval, uint64_t b_aval, uint64_t b_bval, uint64_t* result_aval, uint64_t* result_bval, int is_signed);
    // IEEE 4-state display formatting
    int signal_has_xz(ExecutionContext* ctx, int signal_id);
    const char* fmt_dec_4state(ExecutionContext* ctx, int signal_id, int width, int is_signed);
    const char* fmt_hex_4state(ExecutionContext* ctx, int signal_id, int width);
    const char* fmt_bin_4state(ExecutionContext* ctx, int signal_id, int width);
    
    // Class runtime bridge functions
    void* class_new(ExecutionContext* ctx, const char* class_name);
    void* class_new_with_args(ExecutionContext* ctx, const char* class_name, int64_t* args, int arg_count);
    void* class_new_with_vif(ExecutionContext* ctx, const char* class_name, VirtualInterface* vif);
    void* create_vif(ExecutionContext* ctx, const char* prefix);
    void class_store(ExecutionContext* ctx, const char* var_name, void* instance);
    void* class_load(ExecutionContext* ctx, const char* var_name);
    void* class_copy(ExecutionContext* ctx, void* instance);
    int64_t class_cast(ExecutionContext* ctx, void* dest_instance, void* src_instance, const char* target_class);
    int64_t class_get_static(ExecutionContext* ctx, const char* class_name, const char* member_name);
    void class_set_static(ExecutionContext* ctx, const char* class_name, const char* member_name, int64_t value);
    int64_t class_call_function(ExecutionContext* ctx, void* instance, const char* method_name, int64_t* args, int arg_count);
    void class_call_task(ExecutionContext* ctx, void* instance, const char* method_name, int64_t* args, int arg_count);
}

// Sign extend a value from width bits to 64 bits
static inline int64_t sign_extend(uint64_t value, int width) {
    if (width >= 64) return (int64_t)value;
    uint64_t sign_bit = 1ULL << (width - 1);
    if (value & sign_bit) {
        return (int64_t)(value | (~0ULL << width));
    }
    return (int64_t)value;
}

// Format a value as binary string (for %b in $display)
static inline const char* fmt_binary(uint64_t value, int width) {
    static char bufs[8][65];
    static int buf_idx = 0;
    char* buf = bufs[buf_idx++ & 7];
    if (width == 0) {
        if (value == 0) { buf[0] = '0'; buf[1] = '\0'; return buf; }
        int msb = 0;
        for (int i = 63; i >= 0; i--) { if ((value >> i) & 1) { msb = i; break; } }
        width = msb + 1;
    }
    if (width < 1) width = 1;
    if (width > 64) width = 64;
    buf[width] = '\0';
    for (int i = width - 1; i >= 0; i--) {
        buf[width - 1 - i] = ((value >> i) & 1) ? '1' : '0';
    }
    return buf;
}

static inline const char* fmt_uint_str(uint64_t v) {
    static char bufs[8][24]; static int idx = 0;
    char* buf = bufs[idx++ & 7];
    snprintf(buf, 24, "%llu", (unsigned long long)v);
    return buf;
}
static inline const char* fmt_int_str(int64_t v) {
    static char bufs[8][24]; static int idx = 0;
    char* buf = bufs[idx++ & 7];
    snprintf(buf, 24, "%lld", (long long)v);
    return buf;
}
static inline const char* fmt_hex_str(uint64_t v, int w = 64) {
    static char bufs[8][24]; static int idx = 0;
    char* buf = bufs[idx++ & 7];
    if (w < 64) v &= (1ULL << w) - 1;
    int nchars = (w + 3) / 4;
    if (nchars < 1) nchars = 1;
    if (nchars > 16) nchars = 16;
    snprintf(buf, 24, "%0*llx", nchars, (unsigned long long)v);
    return buf;
}

// Special return values for event control
#define WAIT_FOR_EVENT ((uint64_t)-2)

// Signal ID definitions for this instance
#define SIG_clk 0
#define SIG_internal_clk 2
#define SIG_reset_n 1

// Always block 0 (with delay - state machine)
extern "C" uint64_t eval_always_0(ExecutionContext* ctx, int* state) {
    switch (*state) {
        case 0:
            *state = 1;
            return (10ULL / 2LL);
        case 1:
            _xprop_bval = 0; {
                uint64_t _xp_val = (((~read_signal_xp(ctx, 2))) & ((1ULL << 1) - 1));
                if (_xprop_bval) write_signal_4state_blocking(ctx, 2, 0, ((1ULL << 1) - 1), 1);
                else write_signal_blocking(ctx, 2, _xp_val, 1);
            }
            *state = 2;
            [[fallthrough]];
        case 2:
            *state = 0; // Loop back to start
            return 0;
    }
    return 0;
}

// Always block 1
extern "C" uint64_t eval_always_1(ExecutionContext* ctx, int* state) {
    (void)state; // Unused for non-delay blocks
    if ((!read_signal(ctx, 1))) {
        _xprop_bval = 0; {
            uint64_t _xp_val = ((0LL) & ((1ULL << 1) - 1));
            if (_xprop_bval) write_signal_4state_blocking(ctx, 0, 0, ((1ULL << 1) - 1), 1);
            else write_signal_blocking(ctx, 0, _xp_val, 1);
        }
    } else {
        _xprop_bval = 0; {
            uint64_t _xp_val = ((read_signal_xp(ctx, 2)) & ((1ULL << 1) - 1));
            if (_xprop_bval) write_signal_4state_blocking(ctx, 0, 0, ((1ULL << 1) - 1), 1);
            else write_signal_blocking(ctx, 0, _xp_val, 1);
        }
    }
    return 0; // No delay
}

// Function table for dynamic lookup
// Signature: uint64_t func(ExecutionContext*, int* state)
// Returns delay in time units (0 = no delay, reschedule immediately)
extern "C" {
    typedef uint64_t (*EvalFuncStateful)(ExecutionContext*, int*);
    typedef void (*EvalAssignFunc)(ExecutionContext*);
    
    static EvalFuncStateful _eval_funcs[] = {
        eval_always_0,
        eval_always_1,
        nullptr
    };
    
    
    
    
    EvalFuncStateful get_eval_func(int block_id) {
        if (block_id >= 0 && block_id < 2) {
            return _eval_funcs[block_id];
        }
        return nullptr;
    }
    
    EvalFuncStateful get_initial_func(int block_id) {
        return nullptr;
    }
    
    EvalAssignFunc get_assign_func(int assign_id) {
        return nullptr;
    }
    
    int get_num_always_blocks() {
        return 2;
    }
    
    int get_num_initial_blocks() {
        return 0;
    }
    
    int get_num_assign_blocks() {
        return 0;
    }
    
    EvalFuncStateful get_final_func(int block_id) {
        return nullptr;
    }
    
    int get_num_final_blocks() {
        return 0;
    }
}
